routes/web.php
<?php
namespace App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::prefix('admin')->group(function () {
//group route with middleware "auth"
    Route::group(['middleware' => 'auth'], function() {
        //OBAT
        Route::get('/obat', [ObatController::class,'index'])->name('admin.obat.index');

        //SIGNA
        Route::get('/signa', [SignaController::class,'index'])->name('admin.signa.index');

        //NON RACIKAN
        Route::get('/nonracikan',[nonRacikanController::class,'index'])->name('admin.nonracikan.index');
        Route::get('/nonracikan/tambah',[nonRacikanController::class,'tambah'])->name('admin.nonracikan.tambah');
        Route::post('/nonracikan/simpan',[nonRacikanController::class,'simpan'])->name('admin.nonracikan.simpan');
        Route::delete('/nonracikan/hapus/{id}',[nonRacikanController::class,'hapus'])->name('admin.nonracikan.hapus');
        Route::get('/nonracikan/edit/{id}',[nonRacikanController::class,'edit'])->name('admin.nonracikan.edit');
        Route::post('/nonracikan/{id}',[nonRacikanController::class,'update'])->name('admin.nonracikan.update');
        Route::get('/nonracikan/printpdf',[nonRacikanController::class,'printpdf'])->name('admin.nonracikan.printpdf');

        //BARANG
        Route::get('/catatbarang',[barangController::class,'index'])->name('admin.catatbarang.index');
    });
});

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    use HasFactory;

    protected $table = 'master_barang';
    protected $fillable = [
        'nama_barang',
        'harga_satuan',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarUrlAttribute()
    {
    if ($this->avatar != null) :
    return asset($this->avatar);
    else :
    return 'https://ui-avatars.com/api/?name=' . str_replace(' ', '+',
    $this->name) . '&background=4e73df&color=ffffff&size=100';
    endif;
    }
}

app/Http/Controllers/Admin/barangController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Barang;

class barangController extends Controller
{
    public function index()
    {
        $barang = Barang::all();
        return view('admin.barang.index',['barang' => $barang]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/barang/index.blade.php
@extends('layouts.app', ['title' => 'Transaksi'])

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid mb-5">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold"><i class="fas fa-folder"></i> TRANSAKSI</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.nonracikan.simpan') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                         <div class="transaksi">   
                            <button class="btn btn-primary btn-sm mr-1 add-barang float-right" type="button"><i class="fas fa-plus-circle"></i> Tambah Barang</button>
                            <br>
                            <div class="form-group">   
                                <label for="exampleFormControlSelect2">Barang</label>
                                <select required class="js-example-basic-single" data-width="100%" name="nama_barang[]" >
                                    <option value="">--Pilih Barang--</option>
                                    @foreach($barang as $barangs)
                                    <option data-harga="{{ $barangs->harga_satuan }}"  value="{{ $barang[0]->id }}">{{ $barangs->nama_barang }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Qty</label>
                                <input type="number" name="qty" value="{{ old('name') }}" id="qty" onkeyup="myFunction()" placeholder="Masukkan Qty" class="form-control @error('name') is-invalid @enderror">

                                @error('name')
                                <div class="invalid-feedback" style="display: block">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div id="extra-barang">
                        </div>    
                        <br>
                        <button class="btn btn-primary mr-1 btn-submit" type="submit"><i class="fa fa-paper-plane"></i> SIMPAN</button>
                        <button class="btn btn-warning btn-reset" type="reset"><i class="fa fa-redo"></i> RESET</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

@endsection
@push('js')
    <script>
    const add = document.querySelectorAll(".transaksi .add-barang")
    add.forEach(function(e){
        e.addEventListener('click',function(){
            let element = this.parentElement
            // console.log(element);
            let newElement = document.createElement('div')
                newElement.classList.add('transaksi')
                newElement.innerHTML = `<button class="btn btn-danger btn-sm mr-1 remove-barang float-right" type="button"><i class="fas fa-plus-circle"></i> Remove Barang</button>`
                document.getElementById('extra-barang').appendChild(newElement)
            
            let form1 = document.createElement('div')
                form1.classList.add('form-group')
                form1.classList.add('mb-3')
                form1.innerHTML = `<label for="exampleFormControlSelect2">Barang</label>
                                <select required class="custom-select" name="nama_barang[]">
                                    <option value="">--Pilih Barang--</option>
                                    @foreach($barang as $barangs)
                                    <option data-harga="{{ $barangs->harga_satuan }}">{{ $barangs->nama_barang }}</option>
                                    @endforeach
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button">Button</button>
                                    </div>
                                </select>`
                document.getElementById('extra-barang').appendChild(form1)

            let form2 = document.createElement('div')
                form2.classList.add('form-group')
                form2.innerHTML = `<label>Qty</label>
                                <input type="number" name="qty" value="{{ old('name') }}" id="qty" onkeyup="myFunction()" placeholder="Masukkan Qty" class="form-control @error('name') is-invalid @enderror">

                                @error('name')
                                <div class="invalid-feedback" style="display: block">
                                    {{ $message }}
                                </div>
                                @enderror`
                document.getElementById('extra-barang').appendChild(form2)

            document.querySelector('form').querySelectorAll('.remove-barang ').forEach(function(remove){
                remove.addEventListener('click'.function(elmClick){
                    elmClick.target.form1.remove()
                })
            })
        })
    })
    </script>
@endpush

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="shortcut icon" href="{{ asset('assets/img/shop-2.png') }}" type="image/x-icon">

  <title>{{ $title ?? config('app.name') }} - Admin Kasir</title>

  <!-- Custom fonts for this template-->
  <link href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <!-- Custom styles for this template-->
  <link href="{{ asset('assets/css/sb-admin-2.min.css') }}" rel="stylesheet">
  <link href="{{ asset('assets/css/select2.min.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" integrity="sha512-kq3FES+RuuGoBW3a9R2ELYKRywUEQv0wvPTItv3DSGqjpbNtGWVdvT8qwdKkqvPzT93jp8tSF4+oN4IeTEIlQA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <style>
    .form-control:focus {
      color: #6e707e;
      background-color: #fff;
      border-color: #375dce;
      outline: 0;
      box-shadow: none
    }
    .form-group label {
      font-weight: bold
    }
    #wrapper #content-wrapper {
      background-color: #e2e8f0;
      width: 100%;
      overflow-x: hidden;
    }
    .card-header {
      padding: .75rem 1.25rem;
      margin-bottom: 0;
      background-color: #4e73de;
      border-bottom: 1px solid #e3e6f0;
      color: white;
    }
  </style>

  <!-- jQuery -->
  <script src="{{ asset('assets/vendor/jquery/jquery.min.js') }}"></script>  

  <!-- sweet alert -->
  <script src="{{ asset('assets/js/sweetalert.min.js') }}"></script>  

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon">
          <i class="fas fa-shopping-cart"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Kasir</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Divider -->
      <hr class="sidebar-divider">

      {{-- <!-- Heading -->
      <div class="sidebar-heading">
        OBAT & SIGNA
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item {{ Request::is('admin/obat*') ? ' active' :  '' }} {{ Request::is('admin/signa*') ? ' active' :  '' }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fa fa-shopping-bag"></i>
          <span>OBAT & SIGNA</span>
        </a>
        <div id="collapseTwo" class="collapse {{ Request::is('admin/obat*') ? ' show' :  '' }} {{ Request::is('admin/signa*') ? ' show' :  '' }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">OBAT & SIGNA</h6>
            <a class="collapse-item {{ Request::is('admin/obat*') ? ' active' : '' }}" href="{{ route('admin.obat.index') }}">DATA OBAT</a>
            <a class="collapse-item {{ Request::is('admin/signa*') ? ' active' : '' }}" href="{{ route('admin.signa.index') }}">DATA SIGNA</a>
          </div>
        </div>
      </li> --}}

      <div class="sidebar-heading">
        BARANG & TRANSAKSI
      </div>
{{-- 
      <li class="nav-item {{ Request::is('admin/nonracikan*') ? ' active' :  '' }}">
        <a class="nav-link" href="{{ route('admin.nonracikan.index') }}">
          <i class="fas fa-flask"></i>
          <span>NON RACIKAN</span></a>
      </li> --}}

      <li class="nav-item {{ Request::is('admin/catatbarang*') ? ' active' :  '' }}">
        <a class="nav-link" href="{{ route('admin.catatbarang.index') }}">
          <i class="fas fa-flask"></i>
          <span>CATAT BARANG</span></a>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>


          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                <img class="img-profile rounded-circle" src="{{ auth()->user()->avatar_url }}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  LOGOUT
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        @yield('content')
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>&copy; 2022 Mochamad Rizki Fauzi </span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Apakah Yakin Ingin Keluar ?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Silahkan pilih "Logout" di bawah untuk mengakhiri sesi saat ini.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ route('logout') }}" style="cursor: pointer" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
        </div>
      </div>
    </div>
  </div>
  @stack('before-scripts')

  @stack('js')

  <!-- Bootstrap core JavaScript-->
  <script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ asset('assets/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ asset('assets/js/sb-admin-2.min.js') }}"></script>

  <!-- Page level plugins -->
  <script src="{{ asset('assets/vendor/chart.js/Chart.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script src="{{ asset('assets/js/demo/chart-area-demo.js') }}"></script>
  <script src="{{ asset('assets/js/demo/chart-pie-demo.js') }}"></script>
  <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function() {
    $('.js-example-basic-single').select2({
        theme: "bootstrap"
    });
});
  </script>
  <script>
    $(document).ready( function () {
    $('#myTable').DataTable();
} );
  </script>
  <script>
    //sweetalert for success or error message
    @if(session()->has('success'))
        swal({
            type: "success",
            icon: "success",
            title: "BERHASIL!",
            text: "{{ session('success') }}",
            timer: 1500,
            showConfirmButton: false,
            showCancelButton: false,
            buttons: false,
        });
        @elseif(session()->has('error'))
        swal({
            type: "error",
            icon: "error",
            title: "GAGAL!",
            text: "{{ session('error') }}",
            timer: 1500,
            showConfirmButton: false,
            showCancelButton: false,
            buttons: false,
        });
        @endif
  </script>

  @stack('after-scripts')

</body>

</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1,
shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="{{ asset('assets/img/shop-2.png')
}}" type="image/x-icon">
<title>{{ $title ?? config('app.name') }} - Admin</title>
<!-- Custom fonts for this template-->
<link href="{{ asset('assets/vendor/fontawesomefree/css/all.min.css') }}" rel="stylesheet" type="text/css">
<link
href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,4
00,400i,600,600i,700,700i,800,800i,900,900i"
rel="stylesheet">
<!-- Custom styles for this template-->
<link href="{{ asset('assets/css/sb-admin-2.min.css') }}"
rel="stylesheet">
</head>
<body style="background-color: #e2e8f0;">
@yield('content')
<!-- Bootstrap core JavaScript-->
<script src="{{ asset('assets/vendor/jquery/jquery.min.js')
}}"></script>
<script src="{{
asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js')
}}"></script>
<!-- Core plugin JavaScript-->
<script src="{{ asset('assets/vendor/jqueryeasing/jquery.easing.min.js') }}"></script>
<!-- Custom scripts for all pages-->
<script src="{{ asset('assets/js/sb-admin-2.min.js') }}"></script>
</body>
</html>